### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by mocxlbor** [microsoft/greenlands#9]
how to use?

**Comment by tupini07** [comment]
Hi @mocxlbor thanks for opening this :) it made me realize that we didn't specify in the readme what is the actual goal of this repo. 

At least for now, this repo contains a reference implementation of a system that can be used to collect agent data. The code here is _almost exactly_ the code that was used for the platform used to collect human evaluation data for the [IGLU 2022](https://www.aicrowd.com/challenges/neurips-2022-iglu-challenge) competition,
and while useful, the goal for it is to be a reference implementation that you
can check if you're interested in building something similar, or just want to see
how things work.

That said, we do have some documentation [here](https://github.com/microsoft/greenlands/blob/main/Docs/Home.md). We're still in the process of cleaning it up and making it clearer how to use everything. In the meantime, if you want to run the platform, you'll need to check how to run the different components. I'm afraid there is no single list of steps I can give you, but you can start checking Service and McPlugin which are the components that or on the _server_, and `AgentToolkit` is the library that ML-agents use to communicate with the system. Note that right now you'll also need to setup certain services in Azure on which the platform depends (Service Bus, Cosmos, Blob storage, etc)
